### PR TITLE
add regular meetings agenda & minutes

### PR DESCRIPTION
**Pull request by Dat-Andre**
Added the Agenda and Minutes from all the previous regular meetings.

This is suggestion to organize the folder structure regarding the events

### CODE REVIEW

**Review by rayraspberry — CHANGES_REQUESTED** [review]
I think the format for the name should be:

[YYYYMMDD]-[EventType]-[SubType]-[Doc Type/comment]

Especially if the content is going to be divided into folders by "type" of meeting.
I would suggest not using the word "REGULAR" with regard to organization of the meeting information because  the word REGULAR is subjective.

I would like to stick to objective terms.
INTERNAL 
PUBLIC (or STAGE)
PRIVATE

etc

Examples

20240411-Meeting-Internal-Agenda.md
20240415-Presentation-RFP-CandidateX.md
20240412-Meeting-Internal-Minutes.md
20240212-Meeting-Private-Agenda.md (this could also be notice)

Underscores are acceptable as well imho. 

20240412_Meeting_Internal_Minutes.md

**Comment by Dat-Andre** [comment]
Makes sense. Will update it later today to reflect your insights! Thank you

**Comment by Dat-Andre** [comment]
Tell me what you think about this new structure. 
Also changed the RFP folder names to standardize the use of '-' instead of '_'

**Review by rayraspberry — APPROVED** [review]

**Comment by rayraspberry** [comment]
> Tell me what you think about this new structure. Also changed the RFP folder names to standardize the use of '-' instead of '_'

I'm sorry for leading things down that path of _ or -
Whatever we want to standardize on will work if we find something that is preferred later standardized components can be batch replaced later.

**Pull request merged**
